// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	models "avito-shop/models"

	mock "github.com/stretchr/testify/mock"
)

// InventoryRepositoryInterface is an autogenerated mock type for the InventoryRepositoryInterface type
type InventoryRepositoryInterface struct {
	mock.Mock
}

// AddItem provides a mock function with given fields: username, itemType, quantity
func (_m *InventoryRepositoryInterface) AddItem(username string, itemType string, quantity int) error {
	ret := _m.Called(username, itemType, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int) error); ok {
		r0 = rf(username, itemType, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetInventory provides a mock function with given fields: username
func (_m *InventoryRepositoryInterface) GetInventory(username string) ([]models.InventoryItem, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetInventory")
	}

	var r0 []models.InventoryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.InventoryItem, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) []models.InventoryItem); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.InventoryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInventoryRepositoryInterface creates a new instance of InventoryRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRepositoryInterface {
	mock := &InventoryRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
