// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	models "avito-shop/models"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRepositoryInterface is an autogenerated mock type for the TransactionRepositoryInterface type
type TransactionRepositoryInterface struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: fromUser, toUser, amount
func (_m *TransactionRepositoryInterface) CreateTransaction(fromUser string, toUser string, amount int) error {
	ret := _m.Called(fromUser, toUser, amount)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int) error); ok {
		r0 = rf(fromUser, toUser, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTransactionsForUser provides a mock function with given fields: username
func (_m *TransactionRepositoryInterface) GetTransactionsForUser(username string) ([]models.TransactionHistory, []models.TransactionHistory, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsForUser")
	}

	var r0 []models.TransactionHistory
	var r1 []models.TransactionHistory
	var r2 error
	if rf, ok := ret.Get(0).(func(string) ([]models.TransactionHistory, []models.TransactionHistory, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) []models.TransactionHistory); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TransactionHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(string) []models.TransactionHistory); ok {
		r1 = rf(username)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]models.TransactionHistory)
		}
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(username)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewTransactionRepositoryInterface creates a new instance of TransactionRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepositoryInterface {
	mock := &TransactionRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
